/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CowboyRouteImport } from './routes/cowboy'
import { Route as FindRouteImport } from './routes/find'
import { Route as GroundsRouteImport } from './routes/grounds'
import { Route as ListRouteImport } from './routes/list'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RopeBurnRouteImport } from './routes/rope-burn'
import { Route as TapeRouteImport } from './routes/tape'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDeskRouteImport } from './routes/admin/desk'
import { Route as CutsIndexRouteImport } from './routes/cuts/index'
import { Route as CutsSlugRouteImport } from './routes/cuts/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CowboyRoute = CowboyRouteImport.update({
  id: '/cowboy',
  path: '/cowboy',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const GroundsRoute = GroundsRouteImport.update({
  id: '/grounds',
  path: '/grounds',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RopeBurnRoute = RopeBurnRouteImport.update({
  id: '/rope-burn',
  path: '/rope-burn',
  getParentRoute: () => rootRouteImport,
} as any)
const TapeRoute = TapeRouteImport.update({
  id: '/tape',
  path: '/tape',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDeskRoute = AdminDeskRouteImport.update({
  id: '/admin/desk',
  path: '/admin/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const CutsIndexRoute = CutsIndexRouteImport.update({
  id: '/cuts/',
  path: '/cuts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CutsSlugRoute = CutsSlugRouteImport.update({
  id: '/cuts/$slug',
  path: '/cuts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/cowboy': typeof CowboyRoute
  '/find': typeof FindRoute
  '/grounds': typeof GroundsRoute
  '/list': typeof ListRoute
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/privacy': typeof PrivacyRoute
  '/rope-burn': typeof RopeBurnRoute
  '/tape': typeof TapeRoute
  '/terms': typeof TermsRoute
  '/admin/desk': typeof AdminDeskRoute
  '/cuts/$slug': typeof CutsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/cuts/': typeof CutsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/cowboy': typeof CowboyRoute
  '/find': typeof FindRoute
  '/grounds': typeof GroundsRoute
  '/list': typeof ListRoute
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/privacy': typeof PrivacyRoute
  '/rope-burn': typeof RopeBurnRoute
  '/tape': typeof TapeRoute
  '/terms': typeof TermsRoute
  '/admin/desk': typeof AdminDeskRoute
  '/cuts/$slug': typeof CutsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/cuts': typeof CutsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/cowboy': typeof CowboyRoute
  '/find': typeof FindRoute
  '/grounds': typeof GroundsRoute
  '/list': typeof ListRoute
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/privacy': typeof PrivacyRoute
  '/rope-burn': typeof RopeBurnRoute
  '/tape': typeof TapeRoute
  '/terms': typeof TermsRoute
  '/admin/desk': typeof AdminDeskRoute
  '/cuts/$slug': typeof CutsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/cuts/': typeof CutsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/cowboy'
    | '/find'
    | '/grounds'
    | '/list'
    | '/login'
    | '/merch'
    | '/privacy'
    | '/rope-burn'
    | '/tape'
    | '/terms'
    | '/admin/desk'
    | '/cuts/$slug'
    | '/admin/'
    | '/cuts/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/cowboy'
    | '/find'
    | '/grounds'
    | '/list'
    | '/login'
    | '/merch'
    | '/privacy'
    | '/rope-burn'
    | '/tape'
    | '/terms'
    | '/admin/desk'
    | '/cuts/$slug'
    | '/admin'
    | '/cuts'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/cowboy'
    | '/find'
    | '/grounds'
    | '/list'
    | '/login'
    | '/merch'
    | '/privacy'
    | '/rope-burn'
    | '/tape'
    | '/terms'
    | '/admin/desk'
    | '/cuts/$slug'
    | '/admin/'
    | '/cuts/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CowboyRoute: typeof CowboyRoute
  FindRoute: typeof FindRoute
  GroundsRoute: typeof GroundsRoute
  ListRoute: typeof ListRoute
  LoginRoute: typeof LoginRoute
  MerchRoute: typeof MerchRoute
  PrivacyRoute: typeof PrivacyRoute
  RopeBurnRoute: typeof RopeBurnRoute
  TapeRoute: typeof TapeRoute
  TermsRoute: typeof TermsRoute
  AdminDeskRoute: typeof AdminDeskRoute
  CutsSlugRoute: typeof CutsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CutsIndexRoute: typeof CutsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cowboy': {
      id: '/cowboy'
      path: '/cowboy'
      fullPath: '/cowboy'
      preLoaderRoute: typeof CowboyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grounds': {
      id: '/grounds'
      path: '/grounds'
      fullPath: '/grounds'
      preLoaderRoute: typeof GroundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rope-burn': {
      id: '/rope-burn'
      path: '/rope-burn'
      fullPath: '/rope-burn'
      preLoaderRoute: typeof RopeBurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tape': {
      id: '/tape'
      path: '/tape'
      fullPath: '/tape'
      preLoaderRoute: typeof TapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/desk': {
      id: '/admin/desk'
      path: '/admin/desk'
      fullPath: '/admin/desk'
      preLoaderRoute: typeof AdminDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuts/': {
      id: '/cuts/'
      path: '/cuts'
      fullPath: '/cuts/'
      preLoaderRoute: typeof CutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuts/$slug': {
      id: '/cuts/$slug'
      path: '/cuts/$slug'
      fullPath: '/cuts/$slug'
      preLoaderRoute: typeof CutsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CowboyRoute: CowboyRoute,
  FindRoute: FindRoute,
  GroundsRoute: GroundsRoute,
  ListRoute: ListRoute,
  LoginRoute: LoginRoute,
  MerchRoute: MerchRoute,
  PrivacyRoute: PrivacyRoute,
  RopeBurnRoute: RopeBurnRoute,
  TapeRoute: TapeRoute,
  TermsRoute: TermsRoute,
  AdminDeskRoute: AdminDeskRoute,
  CutsSlugRoute: CutsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  CutsIndexRoute: CutsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
